---
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
    - ".:/app"
    ports:
    - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
    - db
    links:
    - db
    environment:
      RAILS_ENV: development
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306