---
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
    - ".:/app"
    ports:
    - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
    - db
    links:
    - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: db/production.sqlite3
  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/app/db

volumes:
  db_data: