default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: campaign_filter_api_development

test:
  <<: *default
  database: campaign_filter_api_test

production:
  <<: *default
  database: campaign_filter_api_production
  username: <%= ENV['CAMPAIGN_FILTER_API_DATABASE_USERNAME'] %>
  password: <%= ENV['CAMPAIGN_FILTER_API_DATABASE_PASSWORD'] %>
