default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", 'root') %>
  password: <%= ENV.fetch("DB_PASSWORD", 'password') %>
  host: <%= ENV.fetch("DB_HOST", '192.168.1.2') %>
  port: <%= ENV.fetch("PORT", '3307') %>

development:
  <<: *default
  database: campaign_filter_api_development

test:
  <<: *default
  database: campaign_filter_api_test

production:
  <<: *default
  database: campaign_filter_api_production


